blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/3kh0
    about: Join the discord server to meet other people using the website!
  - name: V4 IS COMING
    url: https://discord.gg/3kh0
    about: Soon, v3 is going to be sunset, we are preparing for this by restricting the issues you can make so we can work harder on v4, we hope you enjoy it!
